spring:
  profiles:
    active: default
  config.import: env.properties
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/studentmanagement
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    root: WARN
    com.nvitie: TRACE

stripe.enabled: true